# 1.Print 'Hello HCIA'.

In [1]:
print( 'Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [7]:
a=145
b=12
a+b

157

# 3.Define a list and replicate in three different ways.

In [31]:
import copy
myList=[1,2,3,4,5]
print(myList)

myLis2=myList
print(myLis2)

myLis3=list.copy(myLis2)
print(myLis3)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


# 4.Define two lists and merge them together.

In [11]:
myListOne=[1,2,3,4,5]
myListTwo=[6,7,8,9,10]
mySuperList=myListOne+myListTwo
print(mySuperList)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


# 5. Get the last element of the list and print it.

In [12]:
print(myList[len(myList)-1])

5


# 6.Define a tuple that contains only one element.

In [13]:
aTuple = tuple()
aTuple = ('only one element')
print(aTuple)

only one element


# 7.Define a three-line long string.

In [19]:
s1,s2,s3='long string 1, ','long string 2, ','long string 3'
longString=s1+s2+s3
print(longString)

long string 1, long string 2, long string 3


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [20]:
myTuple = tuple()
myTuple = (1,2,3,'dsds')
for t in myTuple:
    print(t)

1
2
3
dsds


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [21]:
def Mul(a,b):
    return a*b
print(Mul(8,6))

48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [23]:
import numpy as np
array=np.zeros((5, 5))
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [24]:
import numpy as np
array=np.zeros((4, 6))
print(array)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [28]:
arrayString=np.zeros(15)
print('15 : ',arrayString)
arrayString.shape = (3,5)
print('3 x 5: ',arrayString)

15 :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
3 x 5:  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [30]:
arrayOne=np.array([[2, 4], [5, 10], [11, 4]])
arrayTwo=np.array([[12, 44], [0, 17], [1, 1]])
magicArray=arrayOne*arrayTwo
print(magicArray)

[[ 24 176]
 [  0 170]
 [ 11   4]]
